// <auto-generated />
using DesTentesEtDesArbres.ConsoleApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesTentesEtDesArbres.ConsoleApp.Migrations
{
    [DbContext(typeof(DesTentesEtDesArbresContext))]
    [Migration("20220927150730_AddLevelNumber")]
    partial class AddLevelNumber
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("DesTentesEtDesArbres.Core.LevelDefinition", b =>
                {
                    b.Property<uint>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Letter")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerializedPlaygroundInitializer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Height", "Width", "Letter", "Number");

                    b.ToTable("LevelDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
